### ISSUE TITLE
[New Plug-in]: rabbitmq

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf-plugins#34] opened 2018-04-30 14:12 UTC
It would be nice to be able to have multiple versions of rabbitmq managed by asdf. I'm not sure how much trouble it will be to get a rabbitmq service running if rabbitmq is managed by asdf, but it should be possible.

**Comment by w-sanches** [comment] 2019-03-21 19:48
I created this plugin: https://github.com/w-sanches/asdf-rabbitmq

I don't use Rabbitmq so much that I need multiple versions managed at the same time, but I decided to give it a go because I wanted to understand how asdf plugins work and this is a nice opportunity to contribute :D

It probably has some bugs and maybe more people can help. Issue reporting is welcome, I don't know exactly what people are looking for in a rabbitmq plugin for asdf.

**Comment by Stratus3D** [comment] 2019-03-21 20:13
Awesome @w-sanches ! I'll give it a try later tonight.

Looking at the code it looks like you don't need the uninstall script, there is no custom uninstall behavior defined, and asdf will remove the version directory whether or not you define the uninstall script.

**Comment by w-sanches** [comment] 2019-03-21 20:26
This is actually a leftover 👀 

I don't really need this uninstall script right now, but I was testing versions change and I remember I needed to do some cleanup on uninstalls if Rabbitmq was running. If I get to reproduce the error I found I will commit the changes. Otherwise, it is just a harmless script and I am okay with leaving it there.

**Comment by christhekeele** [comment] 2020-11-16 09:34
Say, what's the status of this? Would love to help if it's blocked.

**Comment by jthegedus** [comment] 2021-02-24 08:20
If https://github.com/w-sanches/asdf-rabbitmq is working for everyone, can we get a PR here so we can close this out?

**Comment by Stratus3D** [comment] 2021-02-24 12:55
I created https://github.com/asdf-vm/asdf-plugins/pull/363 for this.

**Closed** 2021-02-24 20:15 UTC
Labels: help wanted
