### ISSUE TITLE
🐛 Let's talk about those Travis CI builds

### ISSUE THREAD

**Issue by canterberry** [asdf-vm/asdf-plugins#84] opened 2019-05-23 17:29 UTC
I'm noticing that builds for this repo have only ever succeeded once -- in [the commit that introduced them](https://github.com/asdf-vm/asdf-plugins/commit/3708af8606bd9009f9aa370b87a44dedd73932a7) on October 18, 2017.

At this point, while I appreciate the intent, I think it's safe to say that after 19 months of consistent failure, the current strategy for Travis CI builds in this repo has proven to be... unfruitful. I mean, why bother with CI if we're just going to ignore the results, right?

So... let's think about what this repo is trying to achieve. From the README:

> "...it's purpose is to serve a list of community maintained _stable_ plugins"

Alright, so this helps us to frame a couple of questions:

 1. How do we **know** if a plugin in the list is unstable?
 2. What do we **do** if a plugin in the list is unstable?

The current Travis CI build does a reasonable job, I think, of answering **1** for us -- require that each plugin have a passing CI build.

Currently, as far as I can tell, nothing is happening for **2**, and that's where it gets interesting.

 1. If one is to strictly abide by the purpose defined in the README, if a plugin is unstable, it should not be presented in the list of plugins at all.
 2. A slightly more lenient option may be to add a flag to `asdf plugin-list-all` to include/exclude unstable plugins (i.e: plugins whose builds are failing).
 3. The most lenient option would be to do what is happening now: show all plugins, regardless of stability (passing/failing builds).

My problem with **1** is that users may be confused when/if plugins they expect to see no longer appear in the list, and it would not be clear to them where to go to investigate/troubleshoot.

My problem with **3** is that the Travis CI builds are meaningless. They're an unenforced policy, with no impact on the project's functionality or behavior.

Of these choices, my preference would be **2**. Although it's more intrusive to `asdf` (i.e: potentially requires an upstream change to add the `--include-unstable` flag), it seems like a decent compromise between the extremes of options 1 (too strict) and 3 (too lenient).

Either way, having a Travis CI build on this repo contingent upon the passing status of **every plugin** is, in my opinion, not the optimal touch point to enforce plugin stability.

Thoughts? Ideas? I've love some feedback (and, really, validation from the repo maintainers) before starting down an implementation path that may turn out to be ill-conceived or against the grain.

**Comment by particledecay** [comment] 2019-09-07 01:14
I found this issue because I was about to open one saying the exact same thing. I just created two PRs to add plugins, and the PRs both failed builds because of plugins entirely outside of my control... that means that until ALL plugins are fixed, NO pull requests will pass tests. That seems ridiculous.

I like the idea of filtering `list-all` somehow with only passing plugins, however... if you look at how long the `bash test.sh` takes to run, you'll see this is pretty prohibitive (we'd send a new request for every official plugin every time we run that command) as it will take forever.

My suggestion would be to leave things as is. BUT... maybe we can build a bot that will automatically open up an issue (or someone does this manually as cleanup) and simply does a "@username your plugin 'blah-blahblah' is marked as a failing plugin. This is a courtesy comment to inform you that your plugin will be automatically removed if it has not passed a build in the next 30 days. Thank you."

We have all the information we need to notify the owners, and give them a chance to fix. If they don't fix within 30 days, maybe we can consider the plugin abandoned and it *should* be removed.

**Comment by Stratus3D** [comment] 2019-10-22 14:01
> My suggestion would be to leave things as is. BUT... maybe we can build a bot that will automatically open up an issue (or someone does this manually as cleanup) and simply does a "@username your plugin 'blah-blahblah' is marked as a failing plugin. This is a courtesy comment to inform you that your plugin will be automatically removed if it has not passed a build in the next 30 days. Thank you."

Yes! This is what I'd like to have. If a plugin is failing but the maintainer is responsive and gets it fixed within a certain window of time I don't think it should be removed. I like the idea of a bot a lot, but it seems like it would be a lot of work, and I'm not even sure where to begin.

**Comment by canterberry** [comment] 2019-10-22 22:17
👆 Sounds like a good candidate for organizing w/Github Projects. It seems totally within the scope of this repo to have something like that, and it would be involve several moving pieces. In the meantime, someone... *looks around*... could design, propose, and run the process manually. 👀

**Comment by Stratus3D** [comment] 2020-04-28 13:50
@imbsky what do you think of all this?

**Comment by jthegedus** [comment] 2021-07-16 03:20
I am going to close this now. I like some of the suggestions in this thread, but the root cause of this issue are no longer present.

**Closed by jthegedus** 2021-07-16 03:20 UTC
